export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const TOGGLE_CART_DRAWER = "TOGGLE_CART_DRAWER";
export const TOGGLE_PAYMENT_MODAL = "TOGGLE_PAYMENT_MODAL";
export const TOGGLE_PAYMENT_COMPLETED = "TOGGLE_PAYMENT_COMPLETED";
export const HANDLE_FORM = "HANDLE_FORM";